### ISSUE TITLE
Let adjust stroke width through props

### ISSUE THREAD

**Issue by Rahuvich** [alex-oleshkevich/vue-tabler-icons#1]
It would be great to have this functionality, I can try to make a PR. What do you think?

**Comment by alex-oleshkevich** [comment]
All custom props are passed to the component directly.
You can set stroke-width like this:

```html
<bold-icon stroke-width="3" />
```

**Comment by alex-oleshkevich** [comment]
Feel free to reopen if you have an alternate idea.
