### ISSUE TITLE
[v1] Missing dev-dependency

### ISSUE THREAD

**Issue by ronaldtveen** [alex-oleshkevich/vue-tabler-icons#10]
Hey,

After I `npm i vue-tabler-icons@^1.0` I get the error below. 
I'm stuck with Vue2 for the moment and I realise this is not a priority of this project any more, but it is either this or a different library, so yeah 🤷🏼‍♂️

```
✖ Mix
  Compiled with some errors in 10.97s

ERROR in ./node_modules/vue-tabler-icons/dist/vue-tabler-icons.es.js 1:0-67
Module not found: Error: Can't resolve '@vue/babel-helper-vue-jsx-merge-props' in '/Users/ronaldt/Sites/crm.test/node_modules/vue-tabler-icons/dist'

webpack compiled with 1 error
```
I temp fixed this by adding the module manually via `npm i -D @vue/babel-helper-vue-jsx-merge-props`, which is [stated](https://www.npmjs.com/package/@vue/babel-helper-vue-jsx-merge-props) it should never be done;
> This tool is used internally and there is no reason for you to ever use it.

It now compiles normally;
```
✔ Compiled Successfully in 10420ms
```

I can now continue migrating the icons over, but still hoping you can correct this somehow?

**Comment by ronaldtveen** [comment]
I see this is a duplicate of an already closed but unresolved issue: https://github.com/alex-oleshkevich/vue-tabler-icons/issues/4

**Comment by alex-oleshkevich** [comment]
I'll add this dependency soon.
