### ISSUE TITLE
Update tabler-icons to v1.53.0

### ISSUE THREAD

**Issue by kadesignlab** [alex-oleshkevich/vue-tabler-icons#11]
Hi there,

Could you please update the library to use `tabler-icons@1.53.0`? There are lots of new icons since v1.14.2 which is currently used.

By the way, thanks for your work, it saves time quite a lot!

**Comment by alex-oleshkevich** [comment]
It uses 1.52 currently. I will update to 1.54 soon

**Comment by kadesignlab** [comment]
I have updated the library to 2.3.0, some icons are still not available.
From the build log:

```
warning  in ./src/App.vue?vue&type=script&lang=js

"export 'UserCircleIcon' was not found in 'vue-tabler-icons'
```

**Comment by BulgarianHealer** [comment]
@kadesignlab  If you're using Vue 2, i can say that @alex-oleshkevich  doesn't support it, like the last update was 8 months ago. :)

**Comment by alex-oleshkevich** [comment]
@kadesignlab does this issue still exist?

**Comment by kadesignlab** [comment]
Seems like new icons are working now.
Thanks a lot, I'll close the issue.
