### ISSUE TITLE
bug: inject all $data into html may cause errors

### ISSUE THREAD

**Issue by nerijunior** [alex-oleshkevich/vue-tabler-icons#20]
In https://github.com/alex-oleshkevich/vue-tabler-icons/blob/master/build.js#L24
```
const allAttrs = {
    ...this.$data,
    width: attrs.width || size,
    height: attrs.height || size,
}
```

`...this.$data` will inject all the available data inside the element and it will cause errors when using libraries/plugins that adds data to Vue components like `@vue/apollo-option`.

Vue Apollo will allow all components in the application to have an `$apolloData` object inside `this.$data` and the Icon will try to put $apolloData inside the `<svg {...allAttrs} ...` tag.

It will cause: 
```
 Failed to execute 'setAttribute' on 'Element': '$apolloData' is not a valid attribute name.
```

**Comment by alex-oleshkevich** [comment]
This made intentionally to let you pass any arguments to the icon component like:
```html
<bold-icon stroke-width="2" data-attr="value">
```
Please make sure that this still works.

**Comment by alex-oleshkevich** [comment]
merged, thanks!
