### ISSUE TITLE
Request: Update to latest Tabler-Icons (v1.x branch)

### ISSUE THREAD

**Issue by ronaldtveen** [alex-oleshkevich/vue-tabler-icons#24]
@codecalm has [released a crazy amount of icons to tabler-icons](https://github.com/tabler/tabler-icons/releases) in the last couple of weeks.

I'm stuck using a Vue2 app in which I would love to use some of those icons too.
Could you do an up-to-date release in the v1.x branch?

**Comment by alex-oleshkevich** [comment]
done
