### ISSUE TITLE
how can i set dynamic icons?

### ISSUE THREAD

**Issue by apithy-isidro-martinez** [alex-oleshkevich/vue-tabler-icons#3]
What is the best way to set the icon name dynamically based on a variable? I tried this way and it works, but I don't know if there's a better way to do it.

```html
<component :is="status ? chevron-right-icon':'chevron-left-icon'" />

<script>
export default {
  data () {
    return {
      status: true
    }
  }
}
</script>
```
If this way is correct, you may update the readme with this info

**Comment by alex-oleshkevich** [comment]
Yes, this is totally fine.
