### ISSUE TITLE
Version 2.1

### ISSUE THREAD

**Issue by mreduar** [alex-oleshkevich/vue-tabler-icons#34]
Hello, first I wanted to thank you for creating the package I have been using it for about a year now, thank you very much for this.

On the other hand, I see that a few weeks ago new [2.0+](https://tabler-icons.io/changelog) versions have been released and I would like to use these new icons. Is there any chance to get an update soon?

**Comment by alex-oleshkevich** [comment]
Releasing. Thanks for the hint.

**Comment by mreduar** [comment]
> Releasing. Thanks for the hint.

Thank you @alex-oleshkevich!
I was checking and I still can't import the new icons you just added. Apparently the `node_modules/vue-tabler-icons/dist/index.d.ts` is not updated yet.

[The new icons do not appear](https://www.npmjs.com/package/vue-tabler-icons?activeTab=explore), and I get the following error message:
` The requested module '/node_modules/.vite/deps/vue-tabler-icons.js?v=3bf7e351' does not provide an export named 'PlayerPlayFilledIcon'`

**Comment by alex-oleshkevich** [comment]
Could you please file a PR? This will speed up the process.
