### ISSUE TITLE
Update to latest Tabler Icons package version

### ISSUE THREAD

**Issue by danieldrave-tixtrack** [alex-oleshkevich/vue-tabler-icons#44]
Could we get the vue tabler icons package updated to include the latest icons from Tabler? The package was last updated a year ago, is this still being actively maintained?

* The NPM package is currently supporting version `2.21.0` (https://www.npmjs.com/package/vue-tabler-icons)
* Tabler current version 3.11.0: https://tabler.io/icons or https://www.npmjs.com/package/@tabler/icons for reference

**Comment by alex-oleshkevich** [comment]
Okay, there are options:
1. use official library - https://tabler.io/docs/icons/vue
2. just copy/paste SVGs into your project

I don't know if this library should exist in 2024. If you need 10-20 icons you will download a huge NPM dependency, which is a waste of disk space and the network. I recommend you to cherry-pick SVGs from Tabler website into your project and you are done, no components or preprocessing are required.

**Comment by danieldrave-tixtrack** [comment]
Thanks for the quick response. We'll take a look at both options and thank you for the recommendations!
