### ISSUE TITLE
use as a plugin but compile only the icons that are used

### ISSUE THREAD

**Issue by apithy-isidro-martinez** [alex-oleshkevich/vue-tabler-icons#7]
actually i use the package as a plugin in NuxtJs like the doc says but this compiles all the icons even those that i'm not using

```js
import Vue from 'vue';
import VueTablerIcons from 'vue-tabler-icons';

Vue.use(VueTablerIcons);
```

i know that the other aproach is import the icon that im going to use like this 

```vue
<script>
    // MyComponent.vue
    import { BoldIcon } from 'vue-tabler-icons';

    export default {
        components: { BoldIcon },
    };
</script>

<template>
    <bold-icon />
</template>
```

but I would like to import only the icons I need into a single file and then that file add it to the vue instance, like fontAwesome does ... is that possible?

**Comment by alex-oleshkevich** [comment]
Yes, you can. For example, in your `index.js` where you do initialize the Vue application just import needed icons and register them globally.

```js
import {BoldIcon, DashboardIcon} from 'vue-tabler-icons';

const app = new Vue();
app.component('BoldIcon', BoldIcon);
app.component('DashboardIcon', DashboardIcon);
// ...
```

**Comment by apithy-isidro-martinez** [comment]
well, register a plugin in Nuxt and it worked, thank you very much for responding quickly.

`tabler-icons.js`

```js
import {
  TagIcon,
  BuildingIcon,
  PlantIcon
} from 'vue-tabler-icons'

import Vue from 'vue'
Vue.component('TagIcon', TagIcon)
Vue.component('BuildingIcon', BuildingIcon)
Vue.component('PlantIcon', PlantIcon)
```

`nuxt.config.js`

```js
...
  plugins: [
    { src: '~/plugins/tabler-icons', mode: 'client' },
  ],
```
