### ISSUE TITLE
[Bug Report] Library doesn't work on IE11 and break application

### ISSUE THREAD

**Issue by snowgiirl** [alex-oleshkevich/vue-tabler-icons#9]
<h2>Environment</h2>
Lib version: 1.9.0<br>
Vue version: 2.6.11<br>
Browsers: IE11<br>
OS: Windows 10<br>
App created with Vue CLI, integrating all babel plugin, have a browserslistrc etc...

<h2>Steps to reproduce</h2>

1.  Create app with Vue CLI, 
2. Add and install vue-tabler-icons
3. Import and display an icon in a template
4. Go to check application on IE11

<h2>Expected Behavior</h2>
Application should worked correctly and icon should be displayed
<h2>Actual Behavior</h2>
Application doesn't work at all, there is an error in Console <strong>':' expected in chunk-vendor.js</strong> (I can see the problem is located at the level of icon imports)
<h2>Other comment</h2>
I think a good configuration of babel should be enough to fix issue

**Comment by alex-oleshkevich** [comment]
Hi @snowgiirl, I will check what's wrong and try to fix it though I haven't had any plans to support IE11.

**Comment by alex-oleshkevich** [comment]
I made several updates, pls test if it works and let me know the result. I don't have IE11, (un)fortunately :(

**Comment by snowgiirl** [comment]
Hi @alex-oleshkevich, I update lib to 1.12.1 but still not working :/
I will try by downloading your code

**Comment by snowgiirl** [comment]
Hello @alex-oleshkevich, I updated the lib to 1.12.1 but it still not working.
I found another way to make work my application : I transpile myself your library by adding the following code in **vue.config.js** :
```
module.exports = {
    transpileDependendencies: ["vue-tabler-icons"]
}
```
So I think you can close the issue and my solution will could serve to someone else.

**Comment by alex-oleshkevich** [comment]
okay, thank you
